apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dropwizard-autoscaling
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: acs-dropwizards
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
